### ISSUE TITLE
Help In regads actiavating mozilla mumbai Community Group in Facebook

### ISSUE THREAD

**Issue by RishuGoenka** [akshatkedia/fresher-foundry#1]
Hello Akshat,

My name is Rishu Goenka.I am working as a rep in Mumbai.
I am writing this in a concern to re-activate Mozilla Mumbai Community.
while going through the different social media links found that for the Mozilla Mumbai Community Facebook Group you as a admin.
I checked further and found that all the access has been shared with the member but still few things are not allowed that's the reason group is quit inactive.

I request you too kindly allow me or someone else also to moderate and manage the group.
Since social media plays a very important role. I request for your corporation.

https://www.facebook.com/groups/592835504135908/?ref=bookmarks

**Comment by RishuGoenka** [comment]
I didn't find any other way to contact you.
Kindly help me out

**Comment by akshatkedia** [comment]
I have made you the admin, Can you please delete this issue, it is irrelevant to this project.

**Comment by RishuGoenka** [comment]
Sorry github doesn't allow to to delete the issue. I can't remove it.

**Comment by akshatkedia** [comment]
Ah! no problem.
